### ISSUE TITLE
Enhancement: Displaying newly added subdomains in Telegram notification  

### ISSUE THREAD

**Issue by ehsandeep** [003random/ICU#2]
Hi @003random, 

Thanks for publishing this project, installed it yesterday and noticed telegram bot only notify how many new subdomains got added after the new scan, it would be nice if you can notify newly added subdomains names within the notification of telegram after the 1st scan, so you can check those subdomains within telegram only.  

![image](https://user-images.githubusercontent.com/8293321/41908429-8df5c286-7961-11e8-871d-8bd8dfae92a6.png)

Thanks!

**Comment by 003random** [comment]
Hey there, @madaratech,
That sounds like a good idea. I think i will implement this the following way:
When there are more then 15 new domains, it will display the count, otherwise it will print the domains.
And when you request the scan results via the bot, I will let it display the domains instead of the count.
Is that alright?
003random,

**Comment by ehsandeep** [comment]
Perfect @003random. 

Additionally, there is an issue with inserting data into DB as well.  

```
-- Done --
error in domains_db.py with main domain; test.com
Traceback (most recent call last):
  File "/root/icu/database/additional_tools/domains_db.py", line 107, in <module>
    cursor.execute("INSERT INTO errors (Domain, ErrorDescription, Error, Script, scan_Id) VALUES (%s, %s, %s, %s, %s) ", (domain, "error in domains_db.py with main domain; "+domain, e, "sublister_to_db.py", scanId))
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1366, "Incorrect integer value: 'NULL' for column 'scan_ID' at row 1")
```

**Comment by 003random** [comment]
Thanks for pointing out. I will fix that as well.

**Comment by 003random** [comment]
Hey @madaratech,
I've implemented this :)
When you request the scan from the bot, you will get the domains instead of a count, if there are not more then 100. 
If a scan finishes, and the amount of new domains is below 15, you will get the domains as well. if there are 15 or more new domains, you will get the count.

Please test this if you want, and let me know if it works as intended. ;)

003random,

**Comment by ehsandeep** [comment]
Hi @003random, 

I justed pulled the repo and tried to run the scan and got the same follwoing error after completing the scan. 

```
-- Done --
error in domains_db.py with main domain; test.com
Traceback (most recent call last):
  File "/root/icu/database/additional_tools/domains_db.py", line 107, in <module>
    cursor.execute("INSERT INTO errors (Domain, ErrorDescription, Error, Script, scan_Id) VALUES (%s, %s, %s, %s, %s) ", (domain, "error in domains_db.py with main domain; "+domain, e, "sublister_to_db.py", scanId))
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1366, "Incorrect integer value: 'NULL' for column 'scan_ID' at row 1")
```

**Comment by 003random** [comment]
Hey @madaratech,
Yes. I still have to fix that issue, but your request is implemented. Please confirm :)
003random,

**Comment by ehsandeep** [comment]
Thank you, and yes just checked, I'm able to see the results within telegram chat only.

**Comment by 003random** [comment]
What do you mean with in the telegram chat only?

**Comment by 003random** [comment]
The requested features are implemented correctly right?

**Comment by ehsandeep** [comment]
Yes, it is. 

Thanks again!
